apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-{{ .Release.Name }}-statefulset
spec:
  replicas: {{ .Values.db.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-db
    spec:
      containers:
        - name: {{ .Values.db.containerName }}
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          ports:
            - containerPort: {{ .Values.db.containerPort }}
          envFrom:
        - configMapRef:
            name: web-{{.Release.Name}}-configmap
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data/
              subPath: postgres
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.db.storageSize }}
