apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-{{ .Release.Name }}-statefulset
spec:
  replicas: {{ .Values.db.replicaCount }}
  selector:
    matchLabels:
      app: db-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: db-{{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.db.containerName }}
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          ports:
            - containerPort: {{ .Values.db.containerPort }}
          resources:
            requests:
              memory: "{{ .Values.web.resources.requests.memory }}"
              cpu: "{{ .Values.web.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.web.resources.limits.memory }}"
              cpu: "{{ .Values.web.resources.limits.cpu }}"
          envFrom:
            - configMapRef:
                name: web-{{ .Release.Name }}-configmap
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data/
              subPath: postgres
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.db.storageSize }}
