apiVersion: v1
kind: Service
metadata:
  name: web-{{ .Release.Name }}-svc-front
  labels:
    app: web-{{ .Release.Name }}-front
spec:
  type: {{ .Values.front.service.type }}
  selector:
    app: web-{{ .Release.Name }}-front
  ports:
    - port: {{ .Values.front.service.port }}
      targetPort: {{ .Values.front.service.targetPort }}
      nodePort: {{ .Values.front.service.nodePort }}
