apiVersion: v1
kind: Service
metadata:
  name: web-{{ .Release.Name }}-api-svc
  labels:
    app: web-{{ .Release.Name }}-api
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app: web-{{ .Release.Name }}-api
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      nodePort: {{ .Values.api.service.nodePort }}
