apiVersion: v1
kind: Service
metadata:
  name: web-vroumvroum-svc-api
spec:
  type: NodePort
  selector:
    app: web-vroumvroum-api
  ports:
    - port: 80
      targetPort: 8001
      nodePort: 30009